# Generated by Django 5.1.2 on 2024-10-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
